### ISSUE TITLE
Some weird error while self hosting.

### ISSUE THREAD

**Issue by Bluelands** [AstreaTSS/RealmsPlayerlistBot#152]
Error Code is
```
C:\Users\PC\Downloads\RealmsPlayerlistBot-main\RealmsPlayerlistBot-main>py main.py
Traceback (most recent call last):
  File "C:\Users\PC\Downloads\RealmsPlayerlistBot-main\RealmsPlayerlistBot-main\main.py", line 92, in <module>
    sentry_sdk.init(dsn=os.environ["SENTRY_DSN"], before_send=default_sentry_filter)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\hub.py", line 120, in _init
    client = Client(*args, **kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\client.py", line 106, in __init__
    self._init_impl()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\client.py", line 128, in _init_impl
    self.transport = make_transport(self.options)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\transport.py", line 534, in make_transport
    return transport_cls(options)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\transport.py", line 142, in __init__
    Transport.__init__(self, options)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\transport.py", line 56, in __init__
    self.parsed_dsn = Dsn(options["dsn"])
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\utils.py", line 200, in __init__
    raise BadDsn("Unsupported scheme %r" % parts.scheme)
sentry_sdk.utils.BadDsn: Unsupported scheme ''

C:\Users\PC\Downloads\RealmsPlayerlistBot-main\RealmsPlayerlistBot-main>pip install xbox-webapi
Requirement already satisfied: xbox-webapi in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (2.0.11)
Requirement already satisfied: aiohttp in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from xbox-webapi) (3.8.3)
Requirement already satisfied: appdirs in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from xbox-webapi) (1.4.4)
Requirement already satisfied: ms-cv in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from xbox-webapi) (0.1.1)
Requirement already satisfied: pydantic in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from xbox-webapi) (1.10.4)
Requirement already satisfied: ecdsa in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from xbox-webapi) (0.18.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->xbox-webapi) (22.2.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->xbox-webapi) (2.1.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->xbox-webapi) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->xbox-webapi) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->xbox-webapi) (1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->xbox-webapi) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->xbox-webapi) (1.3.1)
Requirement already satisfied: six>=1.9.0 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from ecdsa->xbox-webapi) (1.16.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from pydantic->xbox-webapi) (4.4.0)
Requirement already satisfied: idna>=2.0 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->xbox-webapi) (3.4)

C:\Users\PC\Downloads\RealmsPlayerlistBot-main\RealmsPlayerlistBot-main>py main.py
Traceback (most recent call last):
  File "C:\Users\PC\Downloads\RealmsPlayerlistBot-main\RealmsPlayerlistBot-main\main.py", line 92, in <module>
    sentry_sdk.init(dsn=os.environ["SENTRY_DSN"], before_send=default_sentry_filter)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\hub.py", line 120, in _init
    client = Client(*args, **kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\client.py", line 106, in __init__
    self._init_impl()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\client.py", line 128, in _init_impl
    self.transport = make_transport(self.options)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\transport.py", line 534, in make_transport
    return transport_cls(options)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\transport.py", line 142, in __init__
    Transport.__init__(self, options)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\transport.py", line 56, in __init__
    self.parsed_dsn = Dsn(options["dsn"])
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\utils.py", line 200, in __init__
    raise BadDsn("Unsupported scheme %r" % parts.scheme)
sentry_sdk.utils.BadDsn: Unsupported scheme ''
```
and i dont seem to see a solution.

**Comment by AstreaTSS** [comment]
Hey - make sure your "SENTRY_DNS" entry in your `config.toml` isn't empty and is a valid Sentry (sentry.io) URL - Sentry is required for this bot.

**Comment by Bluelands** [comment]
still doesent work here is my config
```
# when using the bot, make sure to rename this to just "config.toml"

MAIN_TOKEN = "hidden"  # your discord bot token, of course!
DIRECTORY_OF_BOT = "FOLDER_PATH"  # the folder where the bot's files are located
LOG_FILE_PATH = "FILE_PATH"  # the location where the log file is stored. it's a text file

DEV_GUILD_ID = 11111111111111111  # guild id that you own and that will not be used for a playerlist
BOT_COLOR = 9093705  # a color to color some embeds and all - it's nice for branding.
SETUP_LINK = "https://github.com/AstreaTSS/RealmsPlayerlistBot/wiki/Server-Setup"  # a link to how to set up the bot for a server
PREMIUM_INFO_LINK = "https://github.com/AstreaTSS/RealmsPlayerlistBot/wiki/Playerlist-Premium-and-How-to-Get-It"  # a link about premium

DB_URL = "POSTGRESDB_URL"  # a url to a postgres database
REDIS_URL = "REDIS_URL"  # url to a redis database
SENTRY_DSN = "hidden" # the dsn for sentry

# these next two are generated by the beginning instructions here:
# https://github.com/OpenXbox/xbox-webapi-python#xbox-webapi
XBOX_CLIENT_ID = "hidden"
XBOX_CLIENT_SECRET = "hidden"

OPENXBL_KEY = "hidden"  # register an account at https://xbl.io/ and you'll get a token to use
TOP_GG_TOKEN = ""  # optional, allows top.gg integration if it exists

# when you use the authentication snippet here:
# https://github.com/OpenXbox/xbox-webapi-python#how-to-use
# you'll get a file with tokens that you can now use
# tokens.json is what you're looking for
XAPI_TOKENS_LOCATION = "FILE_PATH"

# various emojis used throughout the bot. more or less self explanatory
GREEN_CIRCLE_EMOJI="RAW EMOJI STRING"
GRAY_CIRCLE_EMOJI="RAW EMOJI STRING"

# the key used to encrypt premium codes. make this a very strong and random 64 character code
PREMIUM_ENCRYPTION_KEY = "W11bjDMbbl6Z2MhYxJOLdb9hSUx7amnC9hkLXaCtMq0yAeiteGDpLWLUKNuYkwzX"
```

**Comment by AstreaTSS** [comment]
Sorry, this is ultimately a Sentry issue, not a bot issue, so I can't help much. From what I read from Sentry's source code, it's likely an issue with the URL you put for SENTEY_DSN, but anything beyond that should be taken up with Sentry themselves.

**Comment by Bluelands** [comment]
ok thanks for helping i will try and see if the issue is from me or them

**Comment by Bluelands** [comment]
the error is diffrent tho
```
C:\Users\PC\Downloads\RealmsPlayerlistBot-main\RealmsPlayerlistBot-main>py main.py
Traceback (most recent call last):
  File "C:\Users\PC\Downloads\RealmsPlayerlistBot-main\RealmsPlayerlistBot-main\main.py", line 272, in <module>
    asyncio.run(start())
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\PC\Downloads\RealmsPlayerlistBot-main\RealmsPlayerlistBot-main\main.py", line 220, in start
    await Tortoise.init(
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\tortoise\__init__.py", line 533, in init
    config = generate_config(db_url, modules)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\tortoise\backends\base\config_generator.py", line 189, in generate_config
    "connections": {_connection_label: expand_db_url(db_url, testing)},
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\tortoise\backends\base\config_generator.py", line 130, in expand_db_url
    raise ConfigurationError(f"Unknown DB scheme: {url.scheme}")
tortoise.exceptions.ConfigurationError: Unknown DB scheme:
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit
```

**Comment by AstreaTSS** [comment]
This is due to having your Postgres database url not properly set. Again, not a bot issue.

**Comment by Bluelands** [comment]
but one problem i dont know how to get my pgadmin password and username

**Comment by Bluelands** [comment]
never used it before

**Comment by AstreaTSS** [comment]
Hey,

While I appreciate your efforts, the Realm Playerlist Bot is admittedly a very hard bot to set up. There's a lot of moving parts in it, and each part requires at least some prior knowledge of it beforehand.

At least for now, I expect self-hosters to know this knowledge - I'd like to think the names I've given each variable in the config are clear enough to tell you what to get, and at its worst, someone may need to Google something to find what's needed, using their prior programming skills to help them do so. Basically, I expect self-hosters to be intermediates at programming at the very least, and definitely would _not_ recommend this "fresh"/lacking knowledge about databases and developer tools.

I'm going to lock this, since I've explicitly stated that [I'll give little support to self-hosters](https://github.com/AstreaTSS/RealmsPlayerlistBot/wiki/FAQ#can-i-self-host-this). That being said, [the Python Discord](https://discord.com/invite/python) is a good place to get support about Python and the many tools you can use with it, and it may help you with hosting this if you wish to continue.

(Final note: yes, I am planning to make a guide on how to self-host this bot eventually, and make it easier to self-host in general. That isn't a priority right now, though.)
